### ISSUE TITLE
Microformats2 vs. Schema.org

### ISSUE THREAD

**Issue by win0err** [indieweb/indiewebify-me#105]
Why is it suggested to markup content using [microformats2](https://microformats.org/) rather than [schema.org](https://schema.org)?

**Comment by gRegorLove** [comment]
In the IndieWeb community, microformats2 is a common [building block](https://indieweb.org/Category:building-blocks) with several tools consuming and publishing them. For example, many implementations of [Webmention](https://webmention.net/) will consume h-entry to display comments, likes, etc.
