### ISSUE TITLE
h-card validator should prefer representative h-card

### ISSUE THREAD

**Issue by snarfed** [indieweb/indiewebify-me#109]
It looks like the h-card validator currently uses the first h-card it finds on the page. I suspect we instead want it to use the [representative h-card algorithm](https://microformats.org/wiki/representative-h-card-parsing), or if that's too much, at least the top-level h-card. The current result for eg https://indiewebify.me/validate-h-card/?url=https%3A%2F%2Fwebrocker.de shows an h-card with a u-photo from an h-entry, which is misleading, since the representative h-card doesn't have a u-photo.

cc @barnabywalters @gRegorLove

**Comment by gRegorLove** [comment]
Hmm, I thought it should be using representative h-card already. I'll check, thanks!

**Comment by gRegorLove** [comment]
I think something might not have gone right with the deploy after #101 merged -- maybe the dependencies didn't update? I'm not really familiar with how the deploy process works.

On my test version with #101, it's finding the rep h-card correctly: https://iwm.gregoreatworld.com/validate-h-card/?url=https%3A%2F%2Fwebrocker.de
