### ISSUE TITLE
h-card validator doesn't check address

### ISSUE THREAD

**Issue by colintedford** [indieweb/indiewebify-me#33]
The h-card validator appears not to check for address properties (p-locality, etc; see [indiewebifyme's view of my h-card](http://indiewebify.me/validate-h-card/?url=http%3A%2F%2Fcolintedford.com) vs. [glenn jones' parser's](http://glennjones.net/tools/microformats/?url=http%3A%2F%2Fcolintedford.com&filters=h-card&callback=)). @tantek told me in #indiewebcamp that [it just checks the bare minimum for indeweb](http://indiewebcamp.com/irc/2015-01-03#t1420353468262); I think it'd be great if it checked everything but if not a note explaining what it does check would prevent confusion.

**Comment by tantek** [comment]
Agreed! The h-card validator should check all properties listed in http://microformats.org/wiki/h-card#Properties
