### ISSUE TITLE
Instagram test

### ISSUE THREAD

**Issue by xuv** [indieweb/indiewebify-me#42]
The Level1 test does not seem to work with Instagram.
I've tested with my own page: http://xuv.be
And the Instagram account related to it is: https://instagram.com/xuvgram

Don't know if it's because the page is actually rendered in javascript.
Before render: the data is in a long JSON like this (removed most of it for clarity): 

```
[…]
"user":{
   "username":"xuvgram",
   "bio":"Collecting laptops covered with stickers #laptopstickers",
   "website":"http:\/\/xuv.be",
[…]
```

and once rendered:  
`<a data-reactid=".0.0.2.0.0:0:2.0.2.4.0" href="http://xuv.be" rel="nofollow me">http://xuv.be</a>`

(Sorry for the post and re-edit, my fingers slipped on the keyboard)

**Comment by gRegorLove** [comment]
[Discussed](https://chat.indieweb.org/dev/2016-08-02#t1470182387905000) just not testing instagram. Since the link back is generated with JS, this validator isn't going to find it. The Instagram API is locked down now so it can't even really be used for relmeauth.
