### ISSUE TITLE
validate-h-card failing with “can not read property ‘href’ of null” error

### ISSUE THREAD

**Issue by bear** [indieweb/indiewebify-me#43]
reported in IRC earlier ...
#20:23 [number5] hey guys, http://indiewebify.me/validate-h-card/ seems broken right now, give me “can not read property ‘href’ of null” error, I’m using Chrome for Mac 46.0.2490.71

http://indiewebcamp.com/irc/2015-10-15/line/1444965824529

I just tried it with my own h-card and it worked

**Comment by gRegorLove** [comment]
Checked the logs and found that this was for https://brucewang.net/. They indicated it no longer happened as of 2015-11-04. I don't get the error currently. I suspect this was an edge case error with the parser at the time. Closing for now.

https://chat.indieweb.org/2015-11-04#t1446616824313000
