### ISSUE TITLE
Twitter verification doesn't work

### ISSUE THREAD

**Issue by aaronpk** [indieweb/indiewebify-me#47]
Is most likely the same problem as https://github.com/aaronpk/IndieAuth.com/issues/108

**Comment by alias1** [comment]
+1 having this issue

**Comment by aaronpk** [comment]
It looks like this is actually because Twitter is not sending an HTTP redirect for browser user agents. Instead they send an HTTP 200 response and an HTML redirect instead. We can probably easily fix this by not sending a browser-like user agent when fetching t.co URLs, or add support for handing HTML meta redirect responses as well.

**Comment by gRegorLove** [comment]
I think that fetching takes place in the rel-me lib https://github.com/indieweb/rel-me

Also discussion reference: https://chat.indieweb.org/dev/2016-07-26#t1469574949249000

**Comment by gRegorLove** [comment]
Closing since more context captured and soon to be resolved in #52.
