### ISSUE TITLE
rel="me" verification fails on http://www.lifewithalacrity.com/

### ISSUE THREAD

**Issue by kevinmarks** [indieweb/indiewebify-me#52]
The rel="me" links are on twitter and github, and indieauth sees them correctly. Is there some case sensitivity or other anomaly?

**Comment by gRegorLove** [comment]
Duplicate of #47

**Comment by kevinmarks** [comment]
No, Twitter works fine with other sites, and lifewithalacrity.com doesn't work with github either

**Comment by gRegorLove** [comment]
Hm. Perhaps it's something with case-sensitivity. It didn't work for gregorlove.com and I was pretty sure it failed for other domains at the time of the discussion in #47, which is what led me to dig into Twitter's response of 200 with a meta redirect + javascript redirect for some UA.

* http://indiewebify.me/validate-rel-me/?url=http%3A%2F%2FgRegorLove.com Tried both capitalizations; this one matches what's on Twitter, but still fails.

* http://indiewebify.me/validate-rel-me/?url=https%3A%2F%2Faaronparecki.com still fails. Notably his URL on Twitter appears to be http: not https:

* http://indiewebify.me/validate-rel-me/?url=http%3A%2F%2Ftantek.com still fails.

* http://indiewebify.me/validate-rel-me/?url=http%3A%2F%2Fkevinmarks.com works.

**Comment by kevinmarks** [comment]
Another thought would be to return more info on why it failed than just
true/false. Specifically,  finding a link without a rel-me on it is worth
notifying.

**Comment by gRegorLove** [comment]
Well, this is getting weird. @kevinmarks's http://t.co/cjiYwEZLiC returns a 301 where most t.co profile links I've tested recently return a 200 with meta+javascript redirect. Christopher's http://t.co/agsxcOcLry does the latter, so I do think this is #47 and the rel-me library probably needs to be updated to follow meta redirects. I found [this probable explanation](http://markpercival.tumblr.com/post/51560498133/hacking-https-http-referrers) for why Twitter is doing it that way.

**Comment by kevinmarks** [comment]
Oh dear. What a mess. @benward is there anything we can do to placate the
bird gods ?

**Comment by gRegorLove** [comment]
I'm working on a PR to the rel-me library that will fall back to following meta-refresh redirects. Shouldn't be too hard; will follow up with results.

**Comment by gRegorLove** [comment]
Alright, guess I chased that rabbit trail more than was necessary. After testing the rel-me library locally, I learned that cURLing the t.co links is returning the proper redirects. So it was just a case-sensitivity issue after all. 

I verified the fix works for my stylized URL as well as Christopher's. @tantek's and @aaronpk's still fails, because they have t.co link which redirect to http. The rel-me library reports that their backlinks match but are not _secure_. Indiewebify me requires both match **and** secure in order to pass the rel-me check. We could handle that better on indiewebify.me, but I'll leave that for a separate discussion/issue.

**Comment by kevinmarks** [comment]
still failing for me: http://indiewebify.me/validate-rel-me/?url=lifewithalacrity.com

http://indiewebify.me/rel-me-links/?url1=http%3A%2F%2Fwww.lifewithalacrity.com%2F&url2=https%3A%2F%2Ftwitter.com%2FChristopherA

**Comment by gRegorLove** [comment]
@aaronpk will need to deploy the rel-me updates to indiewebify.me

**Comment by kevinmarks** [comment]
fixed now that gRegorLove redeployed it
