### ISSUE TITLE
<link rel="author"...> in <head> not detected as authorship claim

### ISSUE THREAD

**Issue by skpy** [indieweb/indiewebify-me#61]
The h-entry validator states:
> There should also be some way to discover the author of the post — either link to your homepage (which should have your h-card on)from anywhere on the page with rel=author, or optionally embed a p-author h-card in the h-entry.

I have `<link rel="author" href="https://skippy.net/">` in the `<head>` section of my pages.  The validator does not detect this, and instead keeps encouraging me to add an author.

I also tried adding `<a rel="author" class="h-card" href="https://skippy.net/"></a>` to each entry, but the validator didn't detect that, either.

As I am the only author on this domain, it seems extraneous to me to explicitly declare within each h-entry that I am the author.

**Comment by gRegorLove** [comment]
@skpy I'm checking on the first bit about rel=author; I think that's only proposed, so not widely used with h-entry, but I could be wrong.

In your second snippet, though, the class is missing p-author. It should be: `<a rel="author" class="p-author h-card" href="https://skippy.net/"></a>

**Comment by skpy** [comment]
Your reply got truncated / cut off, @gRegorLove.  I assume you meant to say "`<a rel="author" class="p-author h-card" href="https://skippy.net/"></a>` ?  Or do I use just p-author and not h-hard on the class?

The microformats documentation and the indieweb wiki both seems inconclusive about how to do this, based on my reading thus far.

**Comment by kevinmarks** [comment]
If you use p-author h-card it will make a nested h-card. If you use
p-author it will be blank as that says to parse the plaintext. If you use
u-author it will make the url that author value.

**Comment by skpy** [comment]
Got it. If I add `class="p-author h-card"` to the `<a>` tag, the validator sees it and lists my URL as the author, which is good enough.  I've opened the linked PR to polish the language a bit.
