### ISSUE TITLE
The h-card checker does not resolve relative URLs.

### ISSUE THREAD

**Issue by Zegnat** [indieweb/indiewebify-me#68]
This leads to problems where, e.g. for [my homepage](https://indiewebify.me/validate-h-card/?url=vanderven.se%2Fmartijn%2F) it will try to load my photo from `https://indiewebify.me/martijn/martijn.jpg` and link to my homepage within the list of links as `https://indiewebify.me/martijn/`.

**Comment by sknebel** [comment]
This actually not an issue of not resolving relative URLs, but of not normalizing entered URLs. Compare with [an added http://](https://indiewebify.me/validate-h-card/?url=http://vanderven.se%2Fmartijn%2F)
