### ISSUE TITLE
Twitter and Facebook "doesn't link back" when checking upon2020.com

### ISSUE THREAD

**Issue by jernst** [indieweb/indiewebify-me#70]
But `rel="me"` links appear on https://twitter.com/Johannes_Ernst and https://facebook.com/johannes.ernst. However, Twitter's goes to its URL shortener, and Facebook's cannot be dereferenced using `curl` because they apparently intersperse a "do you really want to leave Facebook" page. Maybe that has something to do with it.

**Comment by gRegorLove** [comment]
There's a pending PR that resolves this. See #64

**Comment by aciccarello** [comment]
The linked PR was merged. Can this be closed?
