### ISSUE TITLE
https://indiewebify.me/send-webmentions/ blank after POST

### ISSUE THREAD

**Issue by jernst** [indieweb/indiewebify-me#71]
I enter `upon2020.com` and hit submit. I get a blank page. (HTTP 500 according to my browser)

**Comment by gRegorLove** [comment]
Thanks for reporting! We've run into this a few times. See #46.

**Comment by aaronpk** [comment]
This was using the `MentionClient` library wrong. Fixed in 1e83e1ae19bca882de55bd2702bf77d8c2a921f3
