### ISSUE TITLE
indieweb/indiewebify-me – on representative h-card error, list out found rel-me’s

### ISSUE THREAD

**Issue by dougbeal** [indieweb/indiewebify-me#74]
Representative h-card error can be confusing, and it would help if we layed out the rel-me data on an erroron representative h-card error, list out found rel-me’s. Maybe

`
u-url`

rel-me
rel-me
rel-me

(Originally published at: https://crw.moe/b/Yw)

**Comment by gRegorLove** [comment]
@dougbeal I think some markup got eaten here, can you update?

**Comment by dougbeal** [comment]
I think this is fixed now that all the rel-me’s are displayed?  It does look like I was going to put in a suggestion and never completed it.
