### ISSUE TITLE
representative h-card: add url uid source algorithm

### ISSUE THREAD

**Issue by gRegorLove** [indieweb/indiewebify-me#75]
**Edit:** I missed that there's an h-card version of that page. Refer to http://microformats.org/wiki/representative-h-card-parsing instead.

~For the two methods described on http://microformats.org/wiki/representative-hcard-parsing, indiewebify.me is only doing `#2`. Add support for `#1`.~

> 1. url uid source. The first hCard found which has a "url" property whose value is the url of the page (source) and is also a "uid" property for the hCard, is the representative hCard for the page.
> 2. url and rel me. If the previous step didn't find a representative hCard, then the first hCard with a "url" property that also has the rel="me" relation is the representative hCard for the page.

For reference, dougbeal.com currently has a valid represenative h-card as the `author` of the h-feed using this method. Parse results (minified):

```json
"properties": {
  "author": [
    {
      "value": "Douglas Beal",
      "type": [
        "h-card"
      ],
      "properties": {
        "name": [
          "Douglas Beal"
        ],
        "uid": [
          "https://dougbeal.com/"
        ],
        "url": [
          "https://dougbeal.com/"
        ]
      }
    }
  ],
}
```

**Comment by dougbeal** [comment]
Should the link in validate-h-card.html.php be to http://microformats.org/wiki/representative-h-card-parsing ?

(Originally published at: https://crw.moe/t/1b2)

**Comment by dougbeal** [comment]
Fix wiki link https://github.com/indieweb/indiewebify-me/pull/76

(Originally published at: https://crw.moe/t/1b6)
