### ISSUE TITLE
Twitter rel="me" verification failing

### ISSUE THREAD

**Issue by CodeFoodPixels** [indieweb/indiewebify-me#92]
The rel="me" check for Twitter is failing.

I'm unsure if this is due to Twitter hiding the URL behind their t.co shortener, but when hitting the `rel-me-check` on the site with my domain (https://lukeb.co.uk) and my Twitter URL (https://twitter.com/CodeFoodPixels), the check fails. I have verified that I'm using the correct schemes and that I'm using the correct capitalisation in my Twitter URL (just in case that matters).

Rel-me-check url: https://indiewebify.me/rel-me-check/?url1=https%3A%2F%2Flukeb.co.uk%2F&url2=https%3A%2F%2Ftwitter.com%2FCodeFoodPixels

**Comment by edent** [comment]
I've just run into this too.

https://indiewebify.me/rel-me-check/?url1=https%3A%2F%2Fshkspr.mobi%2Fblog%2F&url2=https%3A%2F%2Ftwitter.com%2Fedent returns `{"pass":false,"response":"does not link back","status":200,"secure":null}`

Seems to be https://github.com/indieweb/indiewebify-me/blob/cf1e969d99dc6ee21aef755186ddd470aa3e7824/web/index.php#L225  

See also #59

**Comment by gRegorLove** [comment]
Twitter removed the `rel=me` attribute on their profile page (https://indieweb.org/rel-me#Twitter), so this check will fail. We should probably include special message about this in the results when a Twitter link is found so people won't think they did something wrong.
