### ISSUE TITLE
Hard to read on mobile

### ISSUE THREAD

**Issue by altano** [indieweb/indiewebify-me#93]
The lack of text wrap on mobile means the site is hard to read whether you zoom in or not. Here’s the layout on iOS, zoomed in and zoomed out:
![82A3795E-94A1-4EF4-9343-3DD64AC72F16](https://user-images.githubusercontent.com/1009/116293567-e87faf80-a74b-11eb-8d00-d7361bf5bb43.png)
![55A626A3-D8A5-4E36-9799-0A7B885FC051](https://user-images.githubusercontent.com/1009/116293573-e9184600-a74b-11eb-9404-71b58d9cabdf.png)

**Comment by aciccarello** [comment]
Looks like the non-responsive version of bootstrap 2 is being used. Switching the import to `bootstrap-responsive.css` would require updating some other styles like the container width and form inputs.
