### ISSUE TITLE
Validate h-card fails on nested h-cards and returns an error 500

### ISSUE THREAD

**Issue by johanbove** [indieweb/indiewebify-me#99]
Was testing my personal site and my home page has a `<main>` HTML element which has the representative `h-card` class name. Within this HTML block I had added a Webmentions integration which also rendered elements, links to the authors sites, as h-card elements. This apparently creates an error situation in the "Validate h-card" test.

Examples, please open in browser.

Successful "validate h-card" test without nested h-card:

- <https://presence-johanbove.vercel.app/>
- <https://indiewebify.me/validate-h-card/?url=https%3A%2F%2Fpresence-johanbove.vercel.app%2F>
- <https://indiewebify.me/validate-h-card/?url=https%3A%2F%2Fjohanbove.info>

Failure test, with nested h-card:

- <https://indiewebify.me/validate-h-card/?url=https%3A%2F%2Fpresence-gqle9t8ex-johanbove.vercel.app%2F>
- <https://presence-gqle9t8ex-johanbove.vercel.app/>

Request Info:

![Screenshot 2022-04-30 230945](https://user-images.githubusercontent.com/922765/166122784-63f7393a-3c6d-44b2-a8d1-7d12c7bcd56f.png)

**Comment by gRegorLove** [comment]
Thanks for the report! I'm checking on this now. Since we're using `barnabywalters/php-mf-cleaner`, we should probably use the [getRepresentativeHCard()](https://github.com/barnabywalters/php-mf-cleaner/blob/master/src/BarnabyWalters/Mf2/Functions.php#L225) method from there.
